[package]
name = 'Safe64'
version = '1.4.0'
upgrade_policy = "immutable"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/move-stdlib"

[addresses]
safe64 = "0xb300848fb3adcc202c6858bf70ed293e2838f634f85b17d8c597643dc6abfe13"