[package]
name = 'Safe64'
version = '1.1.0'
upgrade_policy = "immutable"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/move-stdlib"

[addresses]
safe64 = "0x641955278c3d26696a941c144117ecef61082af2ffcb643a98fff1045de35ebe"