[package]
name = 'Safe64'
version = '1.2.0'
upgrade_policy = "immutable"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "aptos-release-v1.16"
subdir = "aptos-move/framework/move-stdlib"

[addresses]
safe64 = "_"

[dev-addresses]
safe64 = "0x3000"
