[package]
name = 'Safe64'
version = '1.3.0'
upgrade_policy = "immutable"

[dependencies.MoveStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "main"
subdir = "aptos-move/framework/move-stdlib"

[addresses]
safe64 = "0x68c1fa58260483f243df9d1846cbd5e91fb970417816f68026f080aae0f85d14"